# html lang
language: zh-CN

# main menu navigation
menu:
  主页: /index.html
  归档: /archives/index.html
  关于: /about/index.html

site:
  avatar: /img/avator.jpg # head portrait.
  bio: '世界很大，所知甚少。' # you can write something to show in the home index.

social:
  enable: true # true to enable the social media link, show you link to it.
  rss: /atom.xml
  github: https://github.com/Jamyein
  email: https://citrusea.cc/email/index.html

# stylesheets loaded in the <head>
stylesheets:
  - /css/markdown.css
  - /css/july.css
  - /css/waline.css # if use waline, please delete the "#" to use the waline.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.7.0.min.js
  - /js/highlight.min.js
  - /js/transition.js
  # - /js/smooth-scroll.min.js

highlight:
  # ...
  theme: default
  theme_dark: default
prismjs:
  # ...
  theme: default
  theme_dark: default

# atom: atom.xml # website feed.

favicon: /img/favicon.ico # you can change to you ico

waline: 
  enable: true # true to enable the waline
  serverURL: https://waline-1-z7968183.deta.app/ # your comment server url