# html lang
language: zh-CN

# main menu navigation
menu:
  主页: /index.html
  归档: /archives/index.html
  关于: /about/index.html

site:
  banner: /img/banner.jpg # banner map of website. (please annotation this line if you don't need it)
  avatar: https://i.postimg.cc/yNZKS2JQ/heard.jpg # head portrait.

# stylesheets loaded in the <head>
stylesheets:
  - /css/markdown.css
  - /css/july.css
  - /css/waline.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.4.1.min.js
  - /js/highlight-9.13.1.min.js
  - /js/transition.js
  - /js/smooth-scroll.min.js

hljs:
  enable: true # true to enable the plugin
  line_number: false # add line_number in frontend or backend (not recommend, have bugs in special hexo version)
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code

# atom: atom.xml # website feed.

favicon: /img/favicon.ico #修改对应文件夹图标即能修改。
